// ************************* USER ************************* //


### REGISTER USER
POST http://localhost:4000/api/v1/register
Content-Type: application/json

{
    "name" : "James Poudel",
    "email":"james@gmail.com",
    "password" : "anuppoudel"
}

### LOGIN USER
POST http://localhost:4000/api/v1/login
Content-Type: application/json

{
 "email":"anuppoudel@gmail.com",
 "password":"anuppoudel"
}

### LOGOUT USER
GET http://localhost:4000/api/v1/logout

### FOLLOW AND UNFOLLOW USER
GET http://localhost:4000/api/v1/follow/627fbac6cd060e8924a850db


// ************************* POST ************************* //

### CREATE POST
POST http://localhost:4000/api/v1/post/upload
Content-Type: application/json

{
"caption":"Third post here, mate!!!!"
}

### LIKE AND DISLIKE POST
GET http://localhost:4000/api/v1/post/627f4348ded1dd6268f9ba9c

### GET POST OF FOLLOWING USERS
GET http://localhost:4000/api/v1/posts

### DELETE POST 
DELETE http://localhost:4000/api/v1/post/627fa7d1f3d484cbd7e7816c