// ************************* USER ************************* //

POST http://localhost:4000/api/v1/register
Content-Type: application/json

{
    "name" : "Anup Poudel",
    "email":"anuppoudel@gmail.com",
    "password" : "anuppoudel"
}

###
POST http://localhost:4000/api/v1/login
Content-Type: application/json

{
 "email":"anup@gmail.com",
 "password" : "anuppoudel"
}


// ************************* POST ************************* //

###
POST http://localhost:4000/api/v1/post/upload
Content-Type: application/json

{
    "caption":"First post here, mate!!!!"

}