// ************************* USER ************************* //

POST http://localhost:4000/api/v1/register
Content-Type: application/json

{
    "name" : "Anu Poudel",
    "email":"anuppoudel@gmail.com",
    "password" : "anuppoudel"
}

###
POST http://localhost:4000/api/v1/login
Content-Type: application/json

{
 "email":"anuppoudel@gmail.com",
 "password" : "anuppoudel"
}

###
GET http://localhost:4000/api/v1/follow/627fa7e5f3d484cbd7e78171


// ************************* POST ************************* //

###
POST http://localhost:4000/api/v1/post/upload
Content-Type: application/json

{
    "caption":" Second post here, mate!!!!"

}

###
GET http://localhost:4000/api/v1/post/627f4348ded1dd6268f9ba9c

###
DELETE http://localhost:4000/api/v1/post/627fa6a2a6bc1ef151a6d1bf